### ISSUE TITLE
Where to run it ?

### ISSUE THREAD

**Issue by GrandSchtroumpf** [foldable-devices/windowsegments-polyfill#7]
Hello,
After several hours of test I couldn't make this library works. I've try to run it in : 
- Surface Duo Emulator
- Edge Beta browser with experimental "Emulation: Support dual screen mode"

In both cases the `foldablesFeat.spanning` field never change. On my both environment above the [message with the state of the screen is never triggered](https://github.com/foldable-devices/windowsegments-polyfill/blob/master/src/index.js#L60).

**Comment by darktears** [comment]
Sorry I just saw the issue. This polyfill is meant to be run on platforms not supporting the API. The Duo emulator does support the API (if you enable the experimental web platform api flag or if you register to the Microsoft origin trial).
